micronaut:
  application:
    name: morpheus-plugin-site
  server:
    port: 8090
  router:
    static-resources:
      docs:
        enabled: true   
        mapping: "/docs/**"
        paths: "classpath:asciidoc"
     javadocs:
        enabled: true   
        mapping: "/api/**"
        paths: "classpath:javadoc"
      default:
        enabled: true   
        mapping: "/**"  
        paths: "classpath:static"